### ISSUE TITLE
dlopen() failed: libmhash.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chikenare** [varnish/libvmod-digest#47]
It doesn't work for me with dicocker, I already tried with the images of varnish fresh, latest and old
the same problem
![Captura de pantalla 2024-11-16 a la(s) 9 20 18 p m](https://github.com/user-attachments/assets/7330717e-09b9-4e87-9459-941087fe0f85)
![Captura de pantalla 2024-11-16 a la(s) 9 20 26 p m](https://github.com/user-attachments/assets/30d8db3c-d8dc-46dc-aae0-c5c481470a83)

**Comment by chikenare** [comment]
I was removing lib hash-dev at the end and didn't realize
![Captura de pantalla 2024-11-16 a la(s) 9 42 38 p m](https://github.com/user-attachments/assets/7300001b-5c21-48c5-95d1-a7f088bd4c8f)

**Comment by gquintard** [comment]
Glad you figured it!

A couple of notes: `VMOD_DEPS` is already defined, so you only really need to just append `libmhash-dev` to it, so that you can add/remove everything in one go.

Also, you probably realized that, but you need `libmhash-dev` to build, but you need `libmhash` to run. And the latter is a dependcu of the former. So you installed `libmhash` automatically with the dev package, and you removed it automatically with the dev packaged too. If you install it explicitly, it'll stick around when you remove `VMOD_DEPS`
